gripper_controller:
    type: effort_controllers/JointTrajectoryController
    topic: "test"
    joints: [r_gripper_joint, r_gripper_l_finger_joint, r_gripper_r_finger_joint]
    action_monitor_rate: 10.0
    state_publish_rate:  25
    gains:
      r_gripper_joint: {p: 10000, i: 500.0, d: 100.0, i_clamp: 100.0}
      r_gripper_l_finger_joint: {p: 10000, i: 500.0, d: 100.0, i_clamp: 100.0}
      r_gripper_r_finger_joint: {p: 10000, i: 500.0, d: 100.0, i_clamp: 100.0}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      r_gripper_joint: {trajectory: 0.1, goal: 0.1}
      r_gripper_l_finger_joint: {trajectory: 0.1, goal: 0.1}
      r_gripper_r_finger_joint: {trajectory: 0.1, goal: 0.1}

