gripper_controller:
    type: effort_controllers/JointTrajectoryController
    topic: "test"
    joints: [r_gripper_joint, r_gripper_palm_joint, r_gripper_l_finger_joint, r_gripper_r_finger_joint, r_gripper_tool_joint]
    action_monitor_rate: 10.0
    state_publish_rate:  25

